//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oybab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.tb_adminlog = new HashSet<AdminLog>();
            this.tb_adminpay = new HashSet<AdminPay>();
            this.tb_adminpay1 = new HashSet<AdminPay>();
            this.tb_balancepay = new HashSet<BalancePay>();
            this.tb_import = new HashSet<Import>();
            this.tb_importdetail = new HashSet<ImportDetail>();
            this.tb_importpay = new HashSet<ImportPay>();
            this.tb_member = new HashSet<Member>();
            this.tb_memberpay = new HashSet<MemberPay>();
            this.tb_order = new HashSet<Order>();
            this.tb_order1 = new HashSet<Order>();
            this.tb_orderdetail = new HashSet<OrderDetail>();
            this.tb_orderdetail1 = new HashSet<OrderDetail>();
            this.tb_orderpay = new HashSet<OrderPay>();
            this.tb_supplier = new HashSet<Supplier>();
            this.tb_supplierpay = new HashSet<SupplierPay>();
            this.tb_takeout = new HashSet<Takeout>();
            this.tb_takeout1 = new HashSet<Takeout>();
            this.tb_takeout2 = new HashSet<Takeout>();
            this.tb_takeoutdetail = new HashSet<TakeoutDetail>();
            this.tb_takeoutdetail1 = new HashSet<TakeoutDetail>();
            this.tb_takeoutpay = new HashSet<TakeoutPay>();
        }
    
        public long AdminId { get; set; }
        public string AdminNo { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string AdminName0 { get; set; }
        public string AdminName1 { get; set; }
        public string AdminName2 { get; set; }
        public long Lang { get; set; }
        public long Sex { get; set; }
        public string Occupation { get; set; }
        public string Mobile { get; set; }
        public string ImageName { get; set; }
        public string IDNumber { get; set; }
        public string Address0 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public double OfferRate { get; set; }
        public double BalancePrice { get; set; }
        public double SpendPrice { get; set; }
        public double FavorablePrice { get; set; }
        public long Mode { get; set; }
        public string Menu { get; set; }
        public long IsOnlyOwn { get; set; }
        public long Order { get; set; }
        public long IsEnable { get; set; }
        public long AddTime { get; set; }
        public Nullable<long> UpdateTime { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminLog> tb_adminlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminPay> tb_adminpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminPay> tb_adminpay1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalancePay> tb_balancepay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Import> tb_import { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportDetail> tb_importdetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportPay> tb_importpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> tb_member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberPay> tb_memberpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> tb_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> tb_order1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> tb_orderdetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> tb_orderdetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPay> tb_orderpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> tb_supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPay> tb_supplierpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Takeout> tb_takeout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Takeout> tb_takeout1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Takeout> tb_takeout2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakeoutDetail> tb_takeoutdetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakeoutDetail> tb_takeoutdetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakeoutPay> tb_takeoutpay { get; set; }
    }
}
