//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oybab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Balance()
        {
            this.tb_adminpay = new HashSet<AdminPay>();
            this.tb_balancepay = new HashSet<BalancePay>();
            this.tb_importpay = new HashSet<ImportPay>();
            this.tb_memberpay = new HashSet<MemberPay>();
            this.tb_orderpay = new HashSet<OrderPay>();
            this.tb_supplierpay = new HashSet<SupplierPay>();
            this.tb_takeoutpay = new HashSet<TakeoutPay>();
        }
    
        public long BalanceId { get; set; }
        public string BalanceName0 { get; set; }
        public string BalanceName1 { get; set; }
        public string BalanceName2 { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string AccountBank { get; set; }
        public double BalancePrice { get; set; }
        public long BalanceType { get; set; }
        public double RemoveRate { get; set; }
        public long IsBind { get; set; }
        public long AddTime { get; set; }
        public Nullable<long> UpdateTime { get; set; }
        public long HideType { get; set; }
        public long Order { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminPay> tb_adminpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BalancePay> tb_balancepay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportPay> tb_importpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberPay> tb_memberpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPay> tb_orderpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPay> tb_supplierpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakeoutPay> tb_takeoutpay { get; set; }
    }
}
