//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oybab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Database
    {
        public long DatabaseId { get; set; }
        public Nullable<long> TokenId { get; set; }
        public string DatabaseVersion { get; set; }
        public string LastDatabaseVersion { get; set; }
        public Nullable<long> LastDatabaseUpdateTime { get; set; }
        public Nullable<long> MarkType { get; set; }
        public Nullable<long> MarkExpireTime { get; set; }
        public Nullable<long> UpdateTime { get; set; }
        public string Remark { get; set; }
    }
}
