//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oybab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.tb_memberpay = new HashSet<MemberPay>();
            this.tb_order = new HashSet<Order>();
            this.tb_orderpay = new HashSet<OrderPay>();
            this.tb_takeout = new HashSet<Takeout>();
            this.tb_takeoutpay = new HashSet<TakeoutPay>();
        }
    
        public long MemberId { get; set; }
        public string MemberNo { get; set; }
        public string CardNo { get; set; }
        public string Password { get; set; }
        public string MemberName0 { get; set; }
        public string MemberName1 { get; set; }
        public string MemberName2 { get; set; }
        public long Lang { get; set; }
        public long Sex { get; set; }
        public long Occupation { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string ImageName { get; set; }
        public string IDNumber { get; set; }
        public string Address0 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string AddressLocation { get; set; }
        public Nullable<long> AdminId { get; set; }
        public double OfferRate { get; set; }
        public double BalancePrice { get; set; }
        public double MinBalancePrice { get; set; }
        public double MaxBalancePrice { get; set; }
        public double SpendPrice { get; set; }
        public double FavorablePrice { get; set; }
        public long ExpiredTime { get; set; }
        public long IsAllowBorrow { get; set; }
        public long Order { get; set; }
        public long IsEnable { get; set; }
        public long AddTime { get; set; }
        public Nullable<long> UpdateTime { get; set; }
        public string Remark { get; set; }
    
        public virtual Admin tb_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberPay> tb_memberpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> tb_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPay> tb_orderpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Takeout> tb_takeout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakeoutPay> tb_takeoutpay { get; set; }
    }
}
