//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oybab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Printer()
        {
            this.tb_Ppr = new HashSet<Ppr>();
        }
    
        public long PrinterId { get; set; }
        public string PrinterName0 { get; set; }
        public string PrinterName1 { get; set; }
        public string PrinterName2 { get; set; }
        public string PrinterDeviceName { get; set; }
        public string PrinterAddress { get; set; }
        public long PrintType { get; set; }
        public long PrintSize { get; set; }
        public long Lang { get; set; }
        public long Order { get; set; }
        public long IsMain { get; set; }
        public long IsCashDrawer { get; set; }
        public long IsEnable { get; set; }
        public long AddTime { get; set; }
        public Nullable<long> UpdateTime { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ppr> tb_Ppr { get; set; }
    }
}
