//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oybab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakeoutDetail
    {
        public long TakeoutDetailId { get; set; }
        public string ServerTakeoutDetailId { get; set; }
        public Nullable<long> ServerTakeoutDetailSessionId { get; set; }
        public long TakeoutId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> ServerProductId { get; set; }
        public double Price { get; set; }
        public double Count { get; set; }
        public double OriginalTotalPrice { get; set; }
        public double TotalPrice { get; set; }
        public double TotalCostPrice { get; set; }
        public long State { get; set; }
        public long AdminId { get; set; }
        public long DeviceId { get; set; }
        public long Mode { get; set; }
        public string Request { get; set; }
        public long IsPack { get; set; }
        public Nullable<long> ConfirmAdminId { get; set; }
        public Nullable<long> ConfirmDeviceId { get; set; }
        public Nullable<long> ConfirmTime { get; set; }
        public long PrintCount { get; set; }
        public long AddTime { get; set; }
        public Nullable<long> UpdateTime { get; set; }
        public string Remark { get; set; }
    
        public virtual Admin tb_admin { get; set; }
        public virtual Admin tb_admin1 { get; set; }
        public virtual Device tb_device { get; set; }
        public virtual Device tb_device1 { get; set; }
        public virtual Product tb_product { get; set; }
        public virtual Takeout tb_takeout { get; set; }
    }
}
