//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oybab.DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLog
    {
        [JsonIgnore]
        public virtual Admin tb_admin { get; set; }
        [JsonIgnore]
        public virtual Device tb_device { get; set; }

        public long AdminLogId { get; set; }
        public long AdminId { get; set; }
        public long DeviceId { get; set; }
        public long Mode { get; set; }
        public long LogMode { get; set; }
        public long LogType { get; set; }
        public string LogTitle { get; set; }
        public string LogContent { get; set; }
        public long IsEnable { get; set; }
        public long LogTime { get; set; }
        public string Remark { get; set; }
        public long AddTime { get; set; }
        public Nullable<long> UpdateTime { get; set; }
    




       
    }
}
