//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oybab.DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Import()
        {
            this.tb_importdetail = new HashSet<ImportDetail>();
            this.tb_importpay = new HashSet<ImportPay>();
        }


        [JsonIgnore]
        public virtual Device tb_device { get; set; }

        [JsonIgnore]
        public virtual Admin tb_admin { get; set; }

        public long ImportId { get; set; }
        public long State { get; set; }
        public long ImportTime { get; set; }
        public double OriginalTotalPrice { get; set; }
        public double TotalPrice { get; set; }
        public double SupplierPaidPrice { get; set; }
        public double PaidPrice { get; set; }
        public double TotalPaidPrice { get; set; }
        public double BorrowPrice { get; set; }
        public double KeepPrice { get; set; }
        public long AdminId { get; set; }
        public long DeviceId { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public long Mode { get; set; }
        public long PrintCount { get; set; }
        public long AddTime { get; set; }
        public long ReCheckedCount { get; set; }
        public Nullable<long> UpdateTime { get; set; }
        public string Remark { get; set; }
    
       
        public virtual Supplier tb_supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportDetail> tb_importdetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportPay> tb_importpay { get; set; }






       
    }
}
