//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oybab.DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.tb_orderdetail = new HashSet<OrderDetail>();
            this.tb_orderpay = new HashSet<OrderPay>();
        }



        [JsonIgnore]
        public virtual Device tb_device { get; set; }
        [JsonIgnore]
        public virtual Device tb_device1 { get; set; }
        [JsonIgnore]
        public virtual Room tb_room { get; set; }

        [JsonIgnore]
        public virtual Admin tb_admin { get; set; }
        [JsonIgnore]
        public virtual Admin tb_admin1 { get; set; }

        public long OrderId { get; set; }
        public long RoomId { get; set; }
        public long State { get; set; }
        public double OriginalTotalPrice { get; set; }
        public double TotalPrice { get; set; }
        public double PaidPrice { get; set; }
        public double MemberPaidPrice { get; set; }
        public double TotalPaidPrice { get; set; }
        public double BorrowPrice { get; set; }
        public double KeepPrice { get; set; }
        public long Lang { get; set; }
        public long AdminId { get; set; }
        public long DeviceId { get; set; }
        public Nullable<long> MemberId { get; set; }
        public long Mode { get; set; }
        public string Request { get; set; }
        public long IsPack { get; set; }
        public long PersonCount { get; set; }
        public double RoomPrice { get; set; }
        public long IsPayByTime { get; set; }
        public long IsFreeRoomPrice { get; set; }
        public long IsAutoPay { get; set; }
        public long RoomPriceCalcTime { get; set; }
        public Nullable<long> StartTime { get; set; }
        public Nullable<long> EndTime { get; set; }
        public long PrintCount { get; set; }
        public long AddTime { get; set; }
        public long ReCheckedCount { get; set; }
        public Nullable<long> UpdateTime { get; set; }
        public long FinishAdminId { get; set; }
        public long FinishDeviceId { get; set; }
        public Nullable<long> FinishTime { get; set; }
        public string Remark { get; set; }
    
       
        public virtual Member tb_member { get; set; }
       
        public virtual ICollection<OrderDetail> tb_orderdetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPay> tb_orderpay { get; set; }





    }
}
