//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oybab.DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductType()
        {
            this.tb_product = new HashSet<Product>();
            this.tb_producttype1 = new HashSet<ProductType>();
        }




        [JsonIgnore]
        public virtual ICollection<Product> tb_product { get; set; }
        [JsonIgnore]
        public virtual ICollection<ProductType> tb_producttype1 { get; set; }
        [JsonIgnore]
        public virtual ProductType tb_producttype2 { get; set; }

        public long ProductTypeId { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string ProductTypeName0 { get; set; }
        public string ProductTypeName1 { get; set; }
        public string ProductTypeName2 { get; set; }
        public string ImageName { get; set; }
        public long Order { get; set; }
        public long HideType { get; set; }
        public long AddTime { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public Nullable<long> UpdateTime { get; set; }
    
 


    }
}
