//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oybab.DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.tb_importdetail = new HashSet<ImportDetail>();
            this.tb_orderdetail = new HashSet<OrderDetail>();
            this.tb_Ppr = new HashSet<Ppr>();
            this.tb_product1 = new HashSet<Product>();
            this.tb_takeoutdetail = new HashSet<TakeoutDetail>();
        }

        [JsonIgnore]
        public virtual ICollection<ImportDetail> tb_importdetail { get; set; }
        [JsonIgnore]
        public virtual ICollection<OrderDetail> tb_orderdetail { get; set; }
        [JsonIgnore]
        public virtual ICollection<Ppr> tb_Ppr { get; set; }
        [JsonIgnore]
        public virtual ICollection<Product> tb_product1 { get; set; }
        [JsonIgnore]
        public virtual Product tb_product2 { get; set; }
        [JsonIgnore]
        public virtual ProductType tb_producttype { get; set; }
        [JsonIgnore]
        public virtual ICollection<TakeoutDetail> tb_takeoutdetail { get; set; }

        public long ProductId { get; set; }
        public long ProductTypeId { get; set; }
        public string ProductName0 { get; set; }
        public string ProductName1 { get; set; }
        public string ProductName2 { get; set; }
        public string Specification0 { get; set; }
        public string Specification1 { get; set; }
        public string Specification2 { get; set; }
        public string Source0 { get; set; }
        public string Source1 { get; set; }
        public string Source2 { get; set; }
        public string Info0 { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public long ProductServerType { get; set; }
        public long ProductLocalType { get; set; }
        public string ProductLocalHash { get; set; }
        public string ProductServerHash { get; set; }
        public string Barcode { get; set; }
        public long IsScales { get; set; }
        public double Price { get; set; }
        public long PriceChangeMode { get; set; }
        public double PriceUpLimit { get; set; }
        public double PriceDownLimit { get; set; }
        public double CostPrice { get; set; }
        public long CostPriceChangeMode { get; set; }
        public double CostPriceUpLimit { get; set; }
        public double CostPriceDownLimit { get; set; }
        public double BalanceCount { get; set; }
        public double WarningCount { get; set; }
        public long IsBindCount { get; set; }
        public long ExpiredTime { get; set; }
        public long ExpiredTimeCount { get; set; }
        public Nullable<long> ProductParentId { get; set; }
        public double ProductParentCount { get; set; }
        public string ImageName { get; set; }
        public long Order { get; set; }
        public long HideType { get; set; }
        public long AddTime { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public Nullable<long> UpdateTime { get; set; }
    







  
    }
}
